name: senai_sd
description: Projeto desenvolvido para o teste prático do processo seletivo do FIESC.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  line_icons: ^2.0.1
  http: ^0.13.5
  animate_do: ^3.0.2
  provider: ^6.0.5
  circular_clip_route: 

flutter:
  uses-material-design: true
